name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.2'

    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run Proxy
      run: php proxy.php
