name: CI

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  tests:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
    - uses: pmmp/setup-php-action@3.2.0
      with:
        php-version: '8.2'

    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run Proxy
      run: php proxy.php
